package com.example.ui.theme

enum class AppLanguage(val code: String, val displayName: String, val flag: String) {
    PERSIAN("fa", "فارسی", "🦁☀️"),
    ENGLISH("en", "English", "🇺🇸")
}

data class LocalizedStrings(
    // Nav Labels
    val navHome: String,
    val navSearch: String,
    val navPlaylists: String,
    val navLibrary: String,
    val navProfile: String,

    // Home Screen
    val appTitle: String,
    val welcomeGreeting: String,
    val fairShuffleTitle: String,
    val fairShuffleDesc: String,
    val fairShufflePlayAll: String,
    val googleSyncActive: String,
    val featuredPlaylists: String,
    val allTracksTitle: String,
    val freeStreaming: String,
    val top10MonthlyTitle: String,
    val top10MonthlySub: String,
    val streamsCount: String,

    // Player
    val playingFrom: String,
    val fairShuffleActiveBadge: String,
    val queueTitle: String,
    val queueTracksCount: String,
    val lyricsTitle: String,
    val speedLabel: String,
    val queueButtonLabel: String,
    val lyricsButtonLabel: String,
    val equalizerButtonLabel: String,
    val fetchOnlineLyricsLabel: String,
    val noLyricsText: String,
    val sleepTimerTitle: String,
    val sleepTimerDesc: String,
    val sleepTimer15m: String,
    val sleepTimer30m: String,
    val sleepTimer45m: String,
    val sleepTimer60m: String,
    val sleepTimerEndOfSong: String,
    val sleepTimerCancel: String,
    val sleepTimerActive: String,

    // Library & Playlists
    val libraryTitle: String,
    val scanLocalFiles: String,
    val createPlaylistTitle: String,
    val smartPlaylists: String,
    val customPlaylists: String,
    val favoritesPlaylistName: String,
    val favoritesPlaylistDesc: String,
    val downloadedPlaylistName: String,
    val downloadedPlaylistDesc: String,
    val libraryAllTracksTab: String,
    val libraryDownloadedTab: String,
    val libraryLocalStorageTab: String,
    val libraryAlbumsTab: String,
    val libraryArtistsTab: String,
    val libraryScanDeviceTitle: String,
    val libraryScanDeviceSub: String,
    val libraryScanBtn: String,
    val sortByPrefix: String,
    val sortAlphabet: String,
    val sortNewest: String,
    val changeSort: String,
    val playlistNormalPlay: String,
    val playlistFairShuffle: String,
    val playlistTracksCount: String,
    val playlistsLibraryTitle: String,
    val playlistsLibrarySub: String,

    // Equalizer & Themes
    val eqTitle: String,
    val eqCancel: String,
    val eqApply: String,
    val themeDark: String,
    val themeLight: String,
    val themeAmoled: String,
    val themeNeon: String,

    // Search & Downloads
    val webBrowserTab: String,
    val directSearchTab: String,
    val downloadsTab: String,
    val googleInputPlaceholder: String,
    val searchBtn: String,
    val downloadPageBtn: String,
    val noDownloads: String,
    val noDownloadsSub: String,
    val downloadCompletedText: String,

    // Profile & Settings
    val profileTitle: String,
    val profileSub: String,
    val languageSection: String,
    val selectLanguage: String,
    val googleAccountTitle: String,
    val backupToCloud: String,
    val restoreFromCloud: String,
    val themeSelectorTitle: String,
    val equalizerFxTitle: String,
    val yourUsernameLabel: String,
    val saveNameBtn: String,
    val editUsernameHint: String,
    val statsTitle: String,
    val statsTotalTime: String,
    val statsPlaylists: String,

    // Dialogs & Actions
    val editPlaylistTitle: String,
    val playlistNameLabel: String,
    val playlistDescLabel: String,
    val playlistDescOptional: String,
    val chooseCoverImage: String,
    val saveChanges: String,
    val cancel: String,
    val createPlaylistBtn: String,

    // General & Actions
    val play: String,
    val pause: String,
    val searchPlaceholder: String,
    val addToPlaylist: String,
    val addedToFavorites: String,
    val removedFromFavorites: String,
    val noCoverNotice: String,

    // Track Options Menu & Dialogs
    val songInfo: String,
    val playNext: String,
    val addToCurrentQueue: String,
    val addToAQueue: String,
    val addToPlaylists: String,
    val share: String,
    val deletePermanently: String,
    val songInfoTitle: String,
    val titleLabel: String,
    val artistLabel: String,
    val albumLabel: String,
    val filePathLabel: String,
    val ok: String,
    val deleteTrackTitle: String,
    val deleteTrackConfirm: String,
    val deletePermanentlyBtn: String,
    val selectPlaylistTitle: String,
    val shareSubject: String,
    val shareText: String
)

object LanguageManager {
    val PersianStrings = LocalizedStrings(
        navHome = "خانه",
        navSearch = "جستجو",
        navPlaylists = "پلی‌لیست",
        navLibrary = "کتابخانه",
        navProfile = "تنظیمات",

        appTitle = "Nimusic Player",
        welcomeGreeting = "خوش آمدید",
        fairShuffleTitle = "حالت شافل عادلانه (True Fair Shuffle)",
        fairShuffleDesc = "ویژگی ویژه Nimusic: هیچ آهنگی تا زمانی که تمام اهنگ‌های لیست یک‌بار پخش نشوند تکرار نخواهد شد.",
        fairShufflePlayAll = "پخش همه با شافل عادلانه",
        googleSyncActive = "پلی‌لیست‌ها با حساب Google همگام هستند",
        featuredPlaylists = "پلی‌لیست‌های پیشنهادی",
        allTracksTitle = "همه آهنگ‌ها",
        freeStreaming = "پخش رایگان",
        top10MonthlyTitle = "۱۰ آهنگ برتر",
        top10MonthlySub = "آهنگ‌هایی که بیشترین پخش را داشته‌اند",
        streamsCount = "استریم",

        playingFrom = "در حال پخش از لیست",
        fairShuffleActiveBadge = "حالت شافل عادلانه فعال است",
        queueTitle = "صف پخش (Up Next)",
        queueTracksCount = "آهنگ",
        lyricsTitle = "متن ترانه (Lyrics)",
        speedLabel = "سرعت:",
        queueButtonLabel = "صف پخش",
        lyricsButtonLabel = "متن ترانه",
        equalizerButtonLabel = "اکولایزر",
        fetchOnlineLyricsLabel = "دریافت آنلاین 🌐",
        noLyricsText = "[00:05] متن ترانه آفلاین یافت نشد\n[00:10] دکمه «دریافت آنلاین» را لمس کنید تا متن ترانه از اینترنت دریافت شود ✨",
        sleepTimerTitle = "تایمر خواب",
        sleepTimerDesc = "زمان‌بندی خاموشی خودکار پخش موسیقی",
        sleepTimer15m = "۱۵ دقیقه",
        sleepTimer30m = "۳۰ دقیقه",
        sleepTimer45m = "۴۵ دقیقه",
        sleepTimer60m = "۶۰ دقیقه",
        sleepTimerEndOfSong = "پایان آهنگ فعلی",
        sleepTimerCancel = "لغو تایمر خواب",
        sleepTimerActive = "تایمر خواب فعال است",

        libraryTitle = "کتابخانه موسیقی",
        scanLocalFiles = "اسکن حافظه دستگاه",
        createPlaylistTitle = "ساخت پلی‌لیست جدید",
        smartPlaylists = "پلی‌لیست‌های هوشمند",
        customPlaylists = "پلی‌لیست‌های شما",
        favoritesPlaylistName = "موزیک‌های مورد علاقه",
        favoritesPlaylistDesc = "گلچین آهنگ‌های نشان‌شده شما",
        downloadedPlaylistName = "دانلود شده‌ها",
        downloadedPlaylistDesc = "آهنگ‌های آماده برای پخش آفلاین",
        libraryAllTracksTab = "همه آهنگ‌ها",
        libraryDownloadedTab = "دانلود شده",
        libraryLocalStorageTab = "آرشیو محلی",
        libraryAlbumsTab = "آلبوم‌ها",
        libraryArtistsTab = "خوانندگان",
        libraryScanDeviceTitle = "اسکن فایل‌های صوتی دستگاه",
        libraryScanDeviceSub = "جستوجوی موزیک‌های MP3 در حافظه داخلی",
        libraryScanBtn = "اسکن",
        sortByPrefix = "مرتب‌سازی بر اساس:",
        sortAlphabet = "حروف الفبا (A-Z)",
        sortNewest = "جدیدترین‌ها",
        changeSort = "تغییر مرتب‌سازی",
        playlistNormalPlay = "پخش معمولی",
        playlistFairShuffle = "شافل عادلانه",
        playlistTracksCount = "آهنگ",
        playlistsLibraryTitle = "کتابخانه پلی‌لیست‌ها",
        playlistsLibrarySub = "مدیریت و ساخت پلی‌لیست‌های نامحدود با قابلیت کشیدن و رها کردن",
        eqTitle = "تنظیمات اکولایزر حرفه‌ای (Equalizer FX)",
        eqCancel = "انصراف",
        eqApply = "اعمال تنظیمات",
        themeDark = "تم تاریک اسپاتیفای (Dark Theme)",
        themeLight = "تم روشن و تمیز (White / Light Theme)",
        themeAmoled = "تم مشکی مطلق (AMOLED Pure Black)",
        themeNeon = "تم نئون سایبرپانک (Neon Cyberpunk)",
        webBrowserTab = "مرورگر گوگل",
        directSearchTab = "جستوجوی مستقیم",
        downloadsTab = "دانلودها",
        googleInputPlaceholder = "جست‌وجو در گوگل یا آدرس سایت...",
        searchBtn = "سرچ",
        downloadPageBtn = "دانلود از این صفحه",
        noDownloads = "هیچ دانلودی انجام نشده است",
        noDownloadsSub = "می‌توانید از مرورگر گوگل یا جست‌وجوی آنلاین آهنگ دانلود کنید",
        downloadCompletedText = "دانلود تکمیل شد - آماده پخش آفلاین",

        profileTitle = "تنظیمات و حساب کاربری",
        profileSub = "شخصی‌سازی حساب و ظاهر برنامه",
        languageSection = "زبان برنامه (Language)",
        selectLanguage = "انتخاب زبان",
        googleAccountTitle = "همگام‌سازی ابری گوگل",
        backupToCloud = "پشتیبان‌گیری در Google Cloud",
        restoreFromCloud = "بازیابی از Google Cloud",
        themeSelectorTitle = "تم و ظاهر برنامه",
        equalizerFxTitle = "تنظیمات اکولایزر صوتی",
        yourUsernameLabel = "نام کاربری شما",
        saveNameBtn = "ذخیره نام",
        editUsernameHint = "انتخاب نامی که کنار خوش آمدید نمایش داده می‌شود",
        statsTitle = "آمار شنیداری شما",
        statsTotalTime = "مجموع زمان استریم",
        statsPlaylists = "پلی‌لیست‌ها",

        editPlaylistTitle = "ویرایش پلی‌لیست ✏️",
        playlistNameLabel = "نام پلی‌لیست",
        playlistDescLabel = "توضیحات کوتاه",
        playlistDescOptional = "توضیحات کوتاه (اختیاری)",
        chooseCoverImage = "انتخاب کاور از گالری",
        saveChanges = "ذخیره تغییرات",
        cancel = "انصراف",
        createPlaylistBtn = "ایجاد پلی‌لیست",

        play = "پخش",
        pause = "توقف",
        searchPlaceholder = "نام آهنگ، خواننده یا سبک...",
        addToPlaylist = "افزودن به پلی‌لیست",
        addedToFavorites = "به علاقمندی‌ها اضافه شد",
        removedFromFavorites = "از علاقمندی‌ها حذف شد",
        noCoverNotice = "کاور پیش‌فرض خودکار",

        songInfo = "اطلاعات آهنگ",
        playNext = "پخش بعد از آهنگ فعلی",
        addToCurrentQueue = "افزودن به صف پخش فعلی",
        addToAQueue = "افزودن به یک صف",
        addToPlaylists = "افزودن به پلی‌لیست‌ها",
        share = "اشتراک‌گذاری",
        deletePermanently = "حذف کامل از گوشی و برنامه",
        songInfoTitle = "اطلاعات آهنگ 🎵",
        titleLabel = "عنوان",
        artistLabel = "خواننده",
        albumLabel = "آلبوم",
        filePathLabel = "مسیر فایل",
        ok = "باشه",
        deleteTrackTitle = "حذف کامل آهنگ 🗑️",
        deleteTrackConfirm = "آیا اطمینان دارید که می‌خواهید آهنگ «%s» را به طور کامل هم از گوشی و هم از برنامه پاک کنید؟",
        deletePermanentlyBtn = "حذف کامل",
        selectPlaylistTitle = "انتخاب پلی‌لیست",
        shareSubject = "اشتراک‌گذاری آهنگ",
        shareText = "بشنوید: %s اثر %s"
    )

    val EnglishStrings = LocalizedStrings(
        navHome = "Home",
        navSearch = "Download",
        navPlaylists = "Playlists",
        navLibrary = "Library",
        navProfile = "Settings",

        appTitle = "Nimusic Player",
        welcomeGreeting = "Welcome",
        fairShuffleTitle = "True Fair Shuffle Mode",
        fairShuffleDesc = "Nimusic Feature: No track repeats until every song in the queue plays once.",
        fairShufflePlayAll = "Fair Shuffle All Tracks",
        googleSyncActive = "Playlists synced with Google Account",
        featuredPlaylists = "Featured Playlists",
        allTracksTitle = "All Tracks",
        freeStreaming = "Free Streaming",
        top10MonthlyTitle = "Top 10 Tracks",
        top10MonthlySub = "Tracks with the most plays",
        streamsCount = "streams",

        playingFrom = "PLAYING FROM PLAYLIST",
        fairShuffleActiveBadge = "True Fair Shuffle Active",
        queueTitle = "Up Next Queue",
        queueTracksCount = "tracks",
        lyricsTitle = "Lyrics",
        speedLabel = "Speed:",
        queueButtonLabel = "Queue",
        lyricsButtonLabel = "Lyrics",
        equalizerButtonLabel = "Equalizer",
        fetchOnlineLyricsLabel = "Fetch Online 🌐",
        noLyricsText = "[00:05] Offline lyrics not found\n[00:10] Tap 'Fetch Online' to download lyrics from internet ✨",
        sleepTimerTitle = "Sleep Timer",
        sleepTimerDesc = "Schedule music playback to automatically stop",
        sleepTimer15m = "15 minutes",
        sleepTimer30m = "30 minutes",
        sleepTimer45m = "45 minutes",
        sleepTimer60m = "60 minutes",
        sleepTimerEndOfSong = "End of current song",
        sleepTimerCancel = "Turn Off Sleep Timer",
        sleepTimerActive = "Sleep timer active",

        libraryTitle = "Music Library",
        scanLocalFiles = "Scan Device Storage",
        createPlaylistTitle = "Create New Playlist",
        smartPlaylists = "Smart Playlists",
        customPlaylists = "Your Playlists",
        favoritesPlaylistName = "Favorite Songs",
        favoritesPlaylistDesc = "Your starred tracks collection",
        downloadedPlaylistName = "Downloaded",
        downloadedPlaylistDesc = "Offline ready audio tracks",
        libraryAllTracksTab = "All Tracks",
        libraryDownloadedTab = "Downloaded",
        libraryLocalStorageTab = "Local Archive",
        libraryAlbumsTab = "Albums",
        libraryArtistsTab = "Artists",
        libraryScanDeviceTitle = "Scan Device Audio Files",
        libraryScanDeviceSub = "Search for MP3 music files in internal storage",
        libraryScanBtn = "Scan",
        sortByPrefix = "Sort by:",
        sortAlphabet = "Alphabet (A-Z)",
        sortNewest = "Newest First",
        changeSort = "Change Sort",
        playlistNormalPlay = "Normal Play",
        playlistFairShuffle = "Fair Shuffle",
        playlistTracksCount = "tracks",
        playlistsLibraryTitle = "Playlists Library",
        playlistsLibrarySub = "Manage and create unlimited playlists with drag & drop support",
        eqTitle = "Equalizer FX Settings",
        eqCancel = "Cancel",
        eqApply = "Apply Settings",
        themeDark = "Spotify Dark Theme",
        themeLight = "Clean Light Theme",
        themeAmoled = "AMOLED Pure Black Theme",
        themeNeon = "Neon Cyberpunk Theme",
        webBrowserTab = "Google Browser",
        directSearchTab = "Direct Search",
        downloadsTab = "Downloads",
        googleInputPlaceholder = "Search Google or enter web URL...",
        searchBtn = "Search",
        downloadPageBtn = "Download Page",
        noDownloads = "No downloads found",
        noDownloadsSub = "Download tracks using Google Browser or online music search",
        downloadCompletedText = "Download complete - Ready for offline play",

        profileTitle = "User Settings",
        profileSub = "Personalize your account and app appearance",
        languageSection = "App Language",
        selectLanguage = "Select Language",
        googleAccountTitle = "Google Cloud Sync",
        backupToCloud = "Backup to Google Cloud",
        restoreFromCloud = "Restore from Google Cloud",
        themeSelectorTitle = "Theme & Appearance",
        equalizerFxTitle = "Audio Equalizer FX",
        yourUsernameLabel = "Your Username",
        saveNameBtn = "Save Name",
        editUsernameHint = "Choose the name displayed next to Welcome",
        statsTitle = "Listening Stats",
        statsTotalTime = "Total Stream Time",
        statsPlaylists = "Playlists",

        editPlaylistTitle = "Edit Playlist ✏️",
        playlistNameLabel = "Playlist Name",
        playlistDescLabel = "Short Description",
        playlistDescOptional = "Description (Optional)",
        chooseCoverImage = "Select Cover from Gallery",
        saveChanges = "Save Changes",
        cancel = "Cancel",
        createPlaylistBtn = "Create Playlist",

        play = "Play",
        pause = "Pause",
        searchPlaceholder = "Search song, artist, or genre...",
        addToPlaylist = "Add to playlist",
        addedToFavorites = "Added to favorites",
        removedFromFavorites = "Removed from favorites",
        noCoverNotice = "Auto Default Cover",

        songInfo = "Song info",
        playNext = "Play after current song",
        addToCurrentQueue = "Add to currently playing queue",
        addToAQueue = "Add to a queue",
        addToPlaylists = "Add to playlists",
        share = "Share",
        deletePermanently = "Delete permanently",
        songInfoTitle = "Song Info 🎵",
        titleLabel = "Title",
        artistLabel = "Artist",
        albumLabel = "Album",
        filePathLabel = "File Path",
        ok = "OK",
        deleteTrackTitle = "Delete Track 🗑️",
        deleteTrackConfirm = "Are you sure you want to permanently delete track \"%s\" from both device and app?",
        deletePermanentlyBtn = "Delete Permanently",
        selectPlaylistTitle = "Select Playlist",
        shareSubject = "Share Track",
        shareText = "Listen to: %s by %s"
    )

    fun getStrings(language: AppLanguage): LocalizedStrings {
        return when (language) {
            AppLanguage.PERSIAN -> PersianStrings
            AppLanguage.ENGLISH -> EnglishStrings
        }
    }
}
